apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-frontend
  namespace: scalable-weather-app
  labels:
    app: scalable-frontend
spec:
  replicas: 2 # Scalable!
  selector:
    matchLabels:
      app: scalable-frontend
  template:
    metadata:
      labels:
        app: scalable-frontend
    spec:
      containers:
        - name: scalable-weather-app-frontend
          image: scalable-weather-app/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: scalable-frontend
  namespace: scalable-weather-app
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000 # Exposes frontend UI to host machine on port 30000
  selector:
    app: scalable-frontend
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scalable-frontend-hpa
  namespace: scalable-weather-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scalable-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

